services:
  github-runner-v42-net:
    image: ghcr.io/v42-net/github-runner
    env_file: ./compose.env
    secrets:
      - GITHUB_ACCESS_TOKEN
    restart: always
    tty: true
secrets:
  GITHUB_ACCESS_TOKEN:
    file: ../secret.txt

